#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" "*.tsx" "*.js" "*.jsx" "*.css" "*.json" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs pnpm prettier --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

# Run ESLint on staged files
echo "$FILES" | grep -E "\.(js|jsx|ts|tsx)$" | xargs pnpm eslint --fix
